const shirts = [
  {
    title: "Classic White Tee",
    price: "15.99",
    description: "A timeless white t-shirt made from 100% cotton.",
    size: "M",
  },
  {
    title: "Black V-Neck",
    price: "18.99",
    description: "Stylish black V-neck shirt for casual wear.",
    size: "L",
  },
  {
    title: "Striped Polo",
    price: "25.99",
    description: "Blue and white striped polo, perfect for semi-formal events.",
    size: "XL",
  },
  {
    title: "Graphic Tee - Mountain",
    price: "22.99",
    description: "Graphic tee featuring a mountain design.",
    size: "S",
  },
  {
    title: "Red Flannel Shirt",
    price: "30.99",
    description: "Warm and cozy red flannel shirt.",
    size: "M",
  },
  {
    title: "Denim Shirt",
    price: "35.99",
    description: "Classic denim shirt with button closures.",
    size: "L",
  },
  {
    title: "Yellow Henley",
    price: "20.99",
    description: "Bright yellow henley with a three-button placket.",
    size: "XL",
  },
  {
    title: "Oversized Hoodie Shirt",
    price: "40.99",
    description: "Hooded shirt for a relaxed fit and style.",
    size: "L",
  },
  {
    title: "Cotton Crew Neck",
    price: "19.99",
    description: "Soft and comfortable crew neck t-shirt.",
    size: "S",
  },
  {
    title: "Athletic Fit Tee",
    price: "21.99",
    description: "Moisture-wicking athletic t-shirt.",
    size: "M",
  },
  {
    title: "Plaid Short Sleeve",
    price: "27.99",
    description: "Green plaid short-sleeve shirt.",
    size: "L",
  },
  {
    title: "Black and White Raglan",
    price: "23.99",
    description: "Classic baseball-style raglan shirt.",
    size: "XL",
  },
  {
    title: "Long Sleeve Thermal",
    price: "29.99",
    description: "Warm thermal shirt with long sleeves.",
    size: "M",
  },
  {
    title: "Burgundy Button-Up",
    price: "32.99",
    description: "Elegant burgundy button-up shirt.",
    size: "S",
  },
  {
    title: "Graphic Tee - Surfboard",
    price: "24.99",
    description: "Beach-themed graphic t-shirt.",
    size: "L",
  },
  {
    title: "Vintage Band Tee",
    price: "28.99",
    description: "Vintage style band t-shirt.",
    size: "XL",
  },
  {
    title: "Tie-Dye Tee",
    price: "22.99",
    description: "Colorful tie-dye shirt for a retro vibe.",
    size: "M",
  },
  {
    title: "Camo Tee",
    price: "19.99",
    description: "Military-style camo t-shirt.",
    size: "S",
  },
  {
    title: "Grey Muscle Shirt",
    price: "16.99",
    description: "Sleeveless muscle shirt for workouts.",
    size: "L",
  },
  {
    title: "Maroon Oversized Tee",
    price: "26.99",
    description: "Oversized t-shirt in maroon color.",
    size: "XL",
  },
  {
    title: "Lightweight Hoodie",
    price: "34.99",
    description: "Lightweight hoodie shirt for cooler days.",
    size: "M",
  },
  {
    title: "Turtle Neck",
    price: "29.99",
    description: "Black turtle neck for elegant style.",
    size: "S",
  },
  {
    title: "White Dress Shirt",
    price: "45.99",
    description: "Crisp white dress shirt for formal wear.",
    size: "L",
  },
  {
    title: "Linen Beach Shirt",
    price: "38.99",
    description: "Casual linen shirt for beach outings.",
    size: "XL",
  },
  {
    title: "Slim Fit Tee",
    price: "20.99",
    description: "Slim fit t-shirt for a tailored look.",
    size: "M",
  },
  {
    title: "Heathered Grey Tee",
    price: "17.99",
    description: "Soft heathered grey t-shirt.",
    size: "L",
  },
  {
    title: "Neon Green Tank Top",
    price: "15.99",
    description: "Bright tank top for summer.",
    size: "S",
  },
  {
    title: "Checked Shirt",
    price: "33.99",
    description: "Red and black checked shirt for casual occasions.",
    size: "XL",
  },
  {
    title: "Formal Black Shirt",
    price: "49.99",
    description: "Elegant black formal shirt.",
    size: "M",
  },
  {
    title: "Striped Henley",
    price: "26.99",
    description: "Navy striped henley shirt.",
    size: "S",
  },
  {
    title: "Casual Chambray Shirt",
    price: "36.99",
    description: "Casual chambray shirt with a button collar.",
    size: "L",
  },
  {
    title: "Sports Jersey",
    price: "28.99",
    description: "Breathable sports jersey for active wear.",
    size: "XL",
  },
  {
    title: "Pastel Pink Tee",
    price: "18.99",
    description: "Light pastel pink t-shirt.",
    size: "M",
  },
  {
    title: "Urban Style Hoodie",
    price: "42.99",
    description: "Trendy urban hoodie shirt.",
    size: "L",
  },
  {
    title: "Longline Tee",
    price: "25.99",
    description: "Longline t-shirt for modern fashion.",
    size: "XL",
  },
  {
    title: "Slogan Tee",
    price: "22.99",
    description: "T-shirt with a bold slogan print.",
    size: "M",
  },
  {
    title: "Patchwork Tee",
    price: "27.99",
    description: "Unique patchwork design t-shirt.",
    size: "S",
  },
  {
    title: "Baseball Jersey Shirt",
    price: "35.99",
    description: "Baseball-style jersey shirt.",
    size: "L",
  },
  {
    title: "Dark Green Polo",
    price: "28.99",
    description: "Classic dark green polo shirt.",
    size: "XL",
  },
  {
    title: "Floral Hawaiian Shirt",
    price: "40.99",
    description: "Vibrant floral Hawaiian shirt.",
    size: "M",
  },
  {
    title: "Plain Black Tee",
    price: "14.99",
    description: "Basic plain black t-shirt.",
    size: "S",
  },
  {
    title: "White Graphic Tee",
    price: "20.99",
    description: "White t-shirt with a subtle graphic design.",
    size: "L",
  },
  {
    title: "Heavyweight Tee",
    price: "24.99",
    description: "Thick and durable heavyweight t-shirt.",
    size: "XL",
  },
  {
    title: "Yellow Striped Tee",
    price: "19.99",
    description: "Yellow tee with horizontal stripes.",
    size: "M",
  },
  {
    title: "Khaki Work Shirt",
    price: "32.99",
    description: "Durable khaki work shirt.",
    size: "L",
  },
  {
    title: "Ringer Tee",
    price: "21.99",
    description: "Vintage-style ringer t-shirt.",
    size: "S",
  },
  {
    title: "Beige Polo",
    price: "29.99",
    description: "Light beige polo for a semi-formal look.",
    size: "XL",
  },
  {
    title: "Eco-Friendly Tee",
    price: "25.99",
    description: "T-shirt made from sustainable materials.",
    size: "M",
  },
  {
    title: "Fitted Tee",
    price: "19.99",
    description: "Fitted t-shirt for a sleek appearance.",
    size: "L",
  },
];

module.exports = shirts;
